# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(stats)
    library(workflows)
}
b <- board_folder(path = "C:/Users/migue/AppData/Local/Temp/Rtmp0kv5wb/pins-5b2c57d51742")
v <- vetiver_pin_read(b, "cars_mpg", version = "20220618T054100Z-0a720")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
  
  
}
