# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
    library(parsnip)
    library(stats)
    library(workflows)
}
b <- board_folder(path = "C:/Users/migue/AppData/Local/Temp/Rtmp0kgvZS/pins-2f8075fa12fb")
v <- vetiver_pin_read(b, "cars_mpg", version = "20220617T182905Z-0a720")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
